# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-10-16 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codemanagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('ProjectName', models.CharField(max_length=2000)),
                ('Generated', models.CharField(max_length=2000)),
                ('ReportPeriod', models.CharField(max_length=2000)),
                ('TotalCommits', models.CharField(max_length=2000)),
                ('TotalLinesofCode', models.CharField(max_length=2000)),
                ('Age', models.CharField(max_length=2000)),
                ('TotalFiles', models.CharField(max_length=2000)),
                ('Authors', models.CharField(max_length=2000)),
            ],
        ),
    ]
