# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-10-19 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codemanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codestatistical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('Allcommits', models.CharField(max_length=2000)),
                ('Allcodelines', models.CharField(max_length=2000)),
                ('Allfiles', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='codemanagement',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
