# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-10-27 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Codemanagement', '0002_auto_20201019_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='codestatistical',
            name='Projectname',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
